[package]
name = "book_analyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rbook = "0.5.0"
rstest = "0.18.2"
