name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Book Analyzer
      run: cargo build -p book_analyzer --verbose
    
    - name: Test Book Analyzer
      run: cargo test -p book_analyzer --verbose
