name: Build and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Book Analyzer
        run: cargo build -p epub --verbose

      - name: Test Book Analyzer
        run: cargo test -p epub --verbose
